# -*- coding: utf-8 -*-
"""portfolio

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h_A29eN986AnQwW1TyrjOQPAS6iSae91
"""

!pip install flask pyngrok

from flask import Flask, render_template_string, request, redirect
from email.message import EmailMessage
import smtplib

app = Flask(__name__)

HTML_PAGE = '''
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ISVG Bharadwaj - Portfolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

<!-- Header -->
<div class="text-center my-3">
    <h2>Ivaturi Sai Venkata Gowtham Bharadwaj</h2>
    <p>Software Engineer</p>
    <p>
            📞 +91-8332822676 <br>
            ✉️ bharadwaj@example.com <br>
            🔗 <a href="https://www.linkedin.com/in/bharadwaj-ivaturi/" target="_blank">LinkedIn Profile</a>
        </p>
</div>

<!-- Navbar -->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <div class="container-fluid">
        <a class="navbar-brand text-white" href="#">MyPortfolio</a>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav">
                <li class="nav-item me-3">
                    <a class="nav-link text-white" href="#about">About</a>
                </li>
                <li class="nav-item me-3">
                    <a class="nav-link text-white" href="#education">Education</a>
                </li>
                <li class="nav-item me-3">
                    <a class="nav-link text-white" href="#project">Projects</a>
                </li>
                <li class="nav-item me-3">
                    <a class="nav-link text-white" href="#skills">Skills</a>
                </li>
                <li class="nav-item me-3">
                    <a class="nav-link text-white" href="#contact">Contact</a>
                </li>
            </ul>
        </div>
    </div>
</nav>


<!-- About -->
<div class="container py-4" id="about">
    <div class="text-center">
        <h4>About</h4>
    </div>
    <p>A fresher graduated Bachelor of Technology in Computer Science Engineering - Artificial Intelligence and Machine Learning graduate
    student seeking for a career opportunity to continue improving my skills, interested in learning new topics and acquiring experience
    in my field of study.</p>
</div>

<!-- Education -->
<div class="container py-4" id="education">
    <div class="text-center">
        <h4>Education</h4>
    </div>
    <p><strong>SRM University AP</strong> - Bachelor Of Technology in Computer Science Engineering - 7.57/10.0 (2020 - 2024)</p>
    <p><strong>Sasi Educational Institutions</strong> - Board of Intermediate Education - 9.88/10.0 (2018 - 2020)</p>
    <p><strong>Sri Chaitanya High School</strong> - Board of Secondary Education - 9.7/10.0 - 7.57/10.0 (2017 - 2018)</p>
</div>

<!-- Projects -->
<div class="container py-4" id="project">
    <div class="text-center">
        <h4>Projects</h4>
    </div>
    <p><strong>Randomized Algorithm and Simulation</strong></p>
    <ul>
      <li>Propose two new games with cards. Implement the process by using the array of structures on the pack of cards.</li>
      <li>Simulated a fundamental card game and a poker game, with functionalities.</li>
    </ul>

    <p><strong>Multi-Client Socket Programming</strong></p>
    <ul>
      <li>Communication among multiple individuals using their IP addresses.</li>
      <li>Java-based GUI application for real-time messaging between nodes.</li>
    </ul>

    <p><strong>Agricultural Database Management System</strong></p>
    <ul>
      <li>Designed and implemented a relational database schema for agricultural management of optimizing farm management and productivity.
      </li>
    </ul>

    <p><strong>Automated Path Navigation</strong></p>
    <ul>
      <li>Find the shortest route between Romanian cities on a map to determine the minimal distance connections.</li>
    </ul>

    <p><strong>Breast Cancer Image Classification</strong></p>
    <ul>
      <li>A deep learning approach to classify breast cancer images into normal, benign, or malignant categories based on
      region of interest extraction and convolution neural networks.</li>
    </ul>
</div>

<!-- Skills -->
<div class="container py-4" id="skills">
    <div class="text-center">
        <h4>Skills</h4>
    </div>
    <ul>
        <li><strong>Programming Languages</strong>: C, C++, Python, Java</li>
        <li><strong>Backend Technologies</strong>: MySQL</li>
        <li><strong>Concepts</strong>: Data Structures, OOPS, Databases</li>
    </ul>
</div>

<!-- Contact -->
<div class="container py-4" id="contact">
    <div class="text-center">
        <h4>Contact Me</h4>
    </div>
    <form action="/sendemail/" method="POST">
        <input class="form-control my-2" type="text" name="name" placeholder="Your Name" required>
        <input class="form-control my-2" type="email" name="_replyto" placeholder="Your Email" required>
        <input class="form-control my-2" type="text" name="Subject" placeholder="Subject" required>
        <textarea class="form-control my-2" name="message" placeholder="Your Message" required></textarea>
        <button class="btn btn-primary" type="submit">Send</button>
    </form>
</div>

</body>
</html>
'''

@app.route('/')
def index():
  return render_template_string(HTML_PAGE)

@app.route('/sendemail/', methods=["POST"])
def sendemail():
  name = request.form['name']
  subject = request.form['Subject']
  email = request.form['_replyto']
  message = request.form['message']

  your_email = "your_email@gmail.com"
  your_password = "your_app_password"

  msg = EmailMessage()
  msg.set_content(f"Name: {name}\nEmail: {email}\nSubject: {subject}\nMessage:\n{message}")
  msg['Subject'] = f"Portfolio Contact: {subject}"
  msg['From'] = your_email
  msg['To'] = your_email
  try:
    server = smtplib.SMTP("smtp.gmail.com", 587)
    server.starttls()
    server.login(your_email, your_password)
    server.send_message(msg)
    server.quit()
    return "<h4>Email sent successfully!</h4><a href='/'>Go Back</a>"
  except Exception as e:
    return f"<h4>Failed to send email: {e}</h4><a href='/'>Go Back</a>"

from pyngrok import ngrok
import os
ngrok.kill()
os.environ["FLASK_APP"] = "app.py"
ngrok.set_auth_token("30zyBQBi3tMl2gl7XtkNGhdCcxN_6w3p3X1dKe42WBKvygc3C")
public_url = ngrok.connect(5000)
print("Your app is live at:", public_url)
if __name__ == '__main__':
  app.run()